version: '3.8'

services:
  backend:
    build:
      context: ./todo_app_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
      - JWT_SECRET=9wL6olvxyAJ52E-cBhPLzQ
    depends_on:
      - mongo

  frontend:
    build:
      context: ./todo_app_frontend
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
