version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://todoUser:todoPassword@mongo:27017/todoapp?authSource=admin
      - JWT_SECRET=9wL6olvxyAJ52E-cBhPLzQ
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminUser
      MONGO_INITDB_ROOT_PASSWORD: adminPassword
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
